version: '3.8'

services:
  laravel:
    build:
      context: .
    container_name: task-manager-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    command: php artisan serve --host=0.0.0.0 --port=9000
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: task_manager
      DB_USERNAME: taskuser
      DB_PASSWORD: secret
    depends_on:
      - db
  # nginx:
  #   image: nginx:alpine
  #   container_name: task-manager-nginx
  #   ports:
  #     - "9000:80"
  #   volumes:
  #     - .:/var/www/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - laravel
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # frontend:
  #   build:
  #     context: ../task-manager-frontend
  #   container_name: task-manager-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ../task-manager-frontend:/app
  #   working_dir: /app
  #   depends_on:
  #     - laravel

volumes:
  db_data:
